import '../utils/basic_imports.dart';

/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData book = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData travel = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ic_round_email = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solar_chart_outline = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solar_phone_outline = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData solar_settings_bold = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData symbol = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uil_wallet = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData akar_icons_thunder = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bxs_up_arrow = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clarity_dollar_bill_line_1 = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ep_remove_filled = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fluent_money_hand_24_regular = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ion_football = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols_mic = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_charity = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_chat = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mingcute_user_4_fill = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mingcute_wifi_fill = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ph_hand_coins = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slider = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bourse = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData car = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clarity_dollar_bill_line = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData food = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData frame_57 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healthicons_bills = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lets_icons_lamp_light = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lucide_car = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lucide_home = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols_pet_supplies_outline = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mdi_college_outline = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pet = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData material_symbols_travel_rounded = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData salary = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coins = IconData(0xf51e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
